#!/bin/bash
python cv.py cl openness "./cl/personality.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff" 
python cv.py cl openness "./cl/personality.train.arff" "./cl/emotion.train.arff" "./cl/emotion.train.arff"
python cv.py cl conscientiousness "./cl/personality.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff" 
python cv.py cl conscientiousness "./cl/personality.train.arff" "./cl/emotion.train.arff" "./cl/emotion.train.arff"
python cv.py cl extraversion "./cl/personality.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff" 
python cv.py cl extraversion "./cl/personality.train.arff" "./cl/emotion.train.arff" "./cl/emotion.train.arff"
python cv.py cl agreeableness "./cl/personality.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff" 
python cv.py cl agreeableness "./cl/personality.train.arff" "./cl/emotion.train.arff" "./cl/emotion.train.arff"
python cv.py cl neuroticism "./cl/personality.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff" 
python cv.py cl neuroticism "./cl/personality.train.arff" "./cl/emotion.train.arff" "./cl/emotion.train.arff"
python cv.py cl arousal "./cl/emotion.train.arff" "./cl/personality.train.arff" "./cl/personality.train.arff" 
python cv.py cl arousal "./cl/emotion.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff"
python cv.py cl valence "./cl/emotion.train.arff" "./cl/personality.train.arff" "./cl/personality.train.arff" 
python cv.py cl valence "./cl/emotion.train.arff" "./cl/likability.train.arff" "./cl/likability.train.arff"
python cv.py cl likability "./cl/likability.train.arff" "./cl/personality.train.arff" "./cl/personality.train.arff" 
python cv.py cl likability "./cl/likability.train.arff" "./cl/emotion.train.arff" "./cl/emotion.train.arff"
